### ISSUE TITLE
XSS Sanitation / Protection?

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#100]
@bonham000 @Bigghead any thoughts?

**Comment by firgon000** [comment]
What is the threat?

**Comment by no-stack-dub-sack** [comment]
@firgon000 I don't know a whole lot about XSS, but @Bigghead mentioned it to me early on in this process. I would think people attempting to write scripts in our text areas where there is actually some room - bio, mentorship bio, etc.

Not sure what could actually be accomplished if someone did...

**Comment by bonham000** [comment]
Looking for @Bigghead's expertise on this one.

**Comment by Bigghead** [comment]
I've used something simple like express-sanitizer to get rid of script tags on the server.


Some of the things people can easily do with XSS:

- On the more harmless side, somebody can just write a setInterval alert script on a page, making it super annoying to load/unusable.

Or

- A user writes a window.open script that will automatically redirect to a malicious site on page load. Imagine if they got this script saved in their profile page's DB. Everybody that visits their profile gets redirected to a new site.

**Comment by Bigghead** [comment]
Or Helmet.js.

**Comment by bonham000** [comment]
I think React helps sanitize input for us? Like I don't care what script you write in any of our inputs, but it will just show up as that string of text later on...? Try it out on the live demo app if you can `window.open` anything then we'll need to take a second look.

**Comment by no-stack-dub-sack** [comment]
@Bigghead @bonham000 
## FCC Alumni Network CISO: Shav "Big Head" Parta

**Comment by Bigghead** [comment]
lolz

**Comment by Bigghead** [comment]
@bonham000 is right, I just read React helps prevents XSS, as they automatically escape certain html strings in inputs.

**Comment by bonham000** [comment]
React 👑

**Comment by Bigghead** [comment]
React is freakin awesome. That window.open trick broke my voting app the first time

**Comment by bonham000** [comment]
MEEN Stack?

**Comment by Bigghead** [comment]
I've always just used something simple like express-sanitizer to get rid of script tags inside inputs on the server. 

Some of the things people can do with xss: 
- a user can write a script that will redirect to a malicious site automatically upon page load
