### ISSUE TITLE
Outstanding Items / Home Stretch 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#110]
- [ ] weird `/dist/ajv.bundle.js` warning: [apparently being championed happily by Dan](https://github.com/webpack/webpack/issues/1617)
- [ ] there are some failed propTypes warnings in the console in various components
  - about the lingering React `PropTypes` warning, it's possible this is stemming from some package we are relying on that hasn't been updated yet, so I think this is safe to ignore. 
    - @bonham000 see comment below
- [x] organize codebase (ex. `common` components)
- [x] polyfills for ES6 string methods
    - @bonham000 since our polyfill solution didn't work, I'm just replacing any instances of `startsWith` and `endsWith` with `.slice()` as appropriate 
- [x] eliminate other trailing ES Lint warnings
- [x] switch between public + config profile views
- [x] profile page loader issue, fix z-index and explicit size on mobile screens 
- [x] fix issue with case sensitivity / invalid `:username` url params on chat controller and public profile
- [x] chat icons/links in profile ~~and user cards~~ - (see initiatePrivateChat from ChatController)
    - added link in "Contact for Mentorship and Other Requests" box, which is always shown
- [x] top margin to accommodate for stacked navbar on fcc verification page
- [x] toggling user image / skills & interests in Community view on mobile only toggles one way on iPhone: after revealing skills & interests you cannot toggle back to the avatar
- [x] fix navbar responsiveness at tablet resolutions
- [x] margins for “account” page w/ flash messages - addressed but still edge case
- [x] fix spelling in 'Access forbiden!'
- [x] update `index.html` `title` of app & favicon
- [x] change picture on passport login GH page 
  - @bonham000 can we change this to the logo? Right now it's your mug. Which is great... but... 😄 
  - @no-stack-dub-sack sure, wait, what, my picture is on GitHub passport login page? 
  - @bonham000 Yeah, I thought you must have changed something, it's no longer @Bigghead's avatar... hmmm...
  - @no-stack-dub-sack Oh, I think it's for whatever profile the GitHub access keys are associated with. So on the production app right now that will be @bonham000. I guess you should get ready for the @no-stack-dub-sack avatar once we release it then. 
  - @bonham000 is there a way we can do it off of the fcc-alumni github and change the logo to our logo? Or can you not do it from an organization like that I wonder? I can research this. 
- [x] linkedin API issue: probably bump this to production-issues
- [x] revisit location search since added country (Mentorship Search)
- [x] update search to display bio if not mentor (Mentorship Search)
- [x] render message box conditionally based on whether or not user has selected skills (Profile_Config)
- [x] connect mentorship search results to profile pages
- [x] see initiate private chat method in Mentorship search - is this ok?
- [x] delete my account + chat history issue
- [x] remove user from DB when user does not fully authenticate so app doesn't break
- [x] popup for info circle in fcc data table (Public_Profile)
- [x] margins for “about” page w/ flash messages
- [x] margins for “login” page w/ flash messages
- [x] margins for flash messages need to change when navbar is mobile and unstacked
- [x] take away ability to change username on login
- [x] mobile margin for stacked mentorship search fields
- [x] improve mentorship search UI
- [x] flash messages... ughhh - done, I think!

**Comment by no-stack-dub-sack** [comment]
> - toggling user image / skills & interests in Community view on mobile only toggles one way on iPhone: after revealing skills & interests you cannot toggle back to the avatar

@bonham000 have you tried touching the gutters? This does it on Android

**Comment by no-stack-dub-sack** [comment]
> - margins for “account” page w/ flash messages - addressed but still edge case

@bonham000 the only one I know of for sure is in community regarding `fccCerts` and this is because one of our "test users" made their profile private at some point during the dev of this app. Which reminds me, we still need to add a note during initial authentication that profile must also be public or fcc verification will fail.

**Comment by bonham000** [comment]
I think we can optimistically bring this one to a close.
