### ISSUE TITLE
Able to go "back" to protected routes using browser nav after logging out

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#113]
see short screen cast. This is reproducible from any protected route. Have not looked into yet, but I'm guessing that even though we've logged out, the session is still active? 

http://g.recordit.co/Ua1ZC52vfr.gif

**Comment by bonham000** [comment]
Chrome was caching the result of GET `/api/user`. Changing this to a POST request (without posting anything) seems to solve it. The caching behavior can vary across browsers but hopefully this POST will prevent the behavior we saw here.
