### ISSUE TITLE
Issue with Fetching FCC Stats in App

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#120]
<img width="955" alt="screen shot 2017-04-21 at 9 24 00 pm" src="https://cloud.githubusercontent.com/assets/18126719/25301337/e59a561e-26d8-11e7-8736-f51214611426.png">

This is the result when someone navigates away from a Public Profile before some of the `axios` calls return. Of course React catches and suppresses these errors nicely and merely provides warnings for us in the console, but there are still several issues here.

First, we should be properly handling the case where these requests return but the component is unmounted. There are a few solutions which would work for this, but a more important consideration is the following: Currently, this component makes 5 ajax calls to the same freeCodeCamp url and we don't persist the results in any way. Furthermore, this will happen separately for any users viewed or even the same user viewed repeatedly — it's easy to imagine how this could escalate to a high amount of request traffic to freeCodeCamp which doesn't represent legitimate users: a problem for them.

I think this is the real issue here. Minimally, the best solution I can see is:

- Either store the stats in the user database schema and persist them, only fetching once per lifetime of the user.
- Or table that idea in favor of triggering 1 action from this component when it mounts which fetches from the FCC endpoint once and then parses the response data among all these pieces we're looking for. Throw the results in an independent Redux store to persist for the lifetime of that user's app session (this also solves the component unmounting issue: we still save the data). I think this would be a decent intermediate solution because the risk of high traffic to FCC is really only a risk as long as we have a high volume of users, which we won't at initial release (and modifying the user schema is a bigger lift right now: in my view a good post-production feature challenge).

@no-stack-dub-sack ^^^

**Comment by no-stack-dub-sack** [comment]
@bonham000 Another thing we should maybe discuss on a call at some point, I can see how this would be come problematic, but I also like the idea of the data being up to date. If we do go with door number 1, finding some way to refresh periodically would be great. Door number 2, this could work as well, but may have its issues, maybe the first option is better since we'd ultimately have to change it anyway if we ended up with a lot of users.

**Comment by bonham000** [comment]
@no-stack-dub-sack I would go with the second option for now. This won't be a major concern until further down the line and simply abstracting this logic into the Redux layer would be a lot easier than trying to add it to the user model right now.

**Comment by bonham000** [comment]
Closing! 😃
