### ISSUE TITLE
Updates in Profile Config are still slow

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#122]
@no-stack-dub-sack this is definitely apparent on mobile, but you can see it on a normal computer if you just type very quickly in any of the text inputs in the profile preferences. I don't think this has to do with the page being in mobile view, I think it's because we are basically updating the entire user object gets every time any field is updated, even if it is just one key press. So everything re-renders (instead of just the input box that was typed in, which is what we want). Finally, I think because this component is fairly complicated and is rendering so much UI, this degree of re-rendering creates a perceptible lag, especially on weaker devices (mobile).

We should try to devise some solution for this. Perhaps we could separate all the inputs into isolated pieces of state and then merge them back into the user object before passing it off to Redux to save. Or, if each of the child components were React `class`es, they could check with `shouldComponentUpdate` to check manually if their props have changed and see if they should re-render. Becasue we reassign the entire `user` in state, right now the answer is always yes since the props are different, even though for almost all of them the actual values of the props haven't changed. Since I assume the actual DOM rendering is the slow step here, preventing that with `shouldComponentUpdate` may save us. That might be more fun to implement too.

I'm speculating on solutions though I don't know what the best move here is. Maybe if we rewrite in Vue.js we'll see huge performance gains — @Bigghead, I hear it's faster than React. ✌️

**Comment by no-stack-dub-sack** [comment]
@bonham000 Yes, I did notice this actually when I was trying to type fast the other day, so agreed, we need to address this. I feel like I thought of something the other day that seemed like an obvious solution, but now it's slipped my mind. I will put some more though into this and we can brainstorm something up.

**Comment by no-stack-dub-sack** [comment]
@bonham000 upon closer examination of the two options, I think the first is the simplest and most sensible. I like the idea behind the second, but most don't need to be class components, and I'm afraid this way may be less explicit and be a bigger obstacle for future development with folks who don't know the codebase. Think I'm going to go ahead and implement the first suggestion.

**Comment by bonham000** [comment]
@no-stack-dub-sack I just made a PR around this — see it for the notes.

**Comment by no-stack-dub-sack** [comment]
@bonham000 setting your PR to close this. We can revisit if and when this issue persists post-production.
