### ISSUE TITLE
Lists for Skills and Interests Sections

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#13]
We need fully built out lists for both Core Skills and Coding Interests sections. This is what I have so far, feel free to edit this list, but whatever you add, please make bold, so we know what has not been hard coded into the program. As of now, all of these have. Thanks!

### Core Skills:

- Angular
- Backbone
- **C**
- C++
- CSS
- D3
- Ember
- HTML
- Java
- JavaScript
- jQuery
- Less
- Meteor
- MongoDB
- Vue
- NodeJS
- PHP
- Python
- Rails
- React
- React-Router
- Redux
- Ruby
- SASS
- SQL
- ThreeJS
- PostgreSQL
- Redis
- Web Sockets
- Express
- Go
- R
- MatLab
- Groovy
- CoffeeScript
- TypeScript
- Scala
- C
- Lua
- Objective-C
- Swift

### Coding Interest:

- Behavior Driven Development
- Big Data
- Blockchain / Bitcoin / Digital Currency
- Data Science
- DevOps
- Game Development
- Internet of Things (IoT)
- Machine Learning / Artificial Intelligence
- QA / Testing
- Test Driven Development
- UI Design
- User Experience
- Virtual / Augmented Reality
- Data Structures
- Algorithms
- Databases
- Distributed Systems
- Scaling
- AWS
- Mobile Dev
- OOP / OOD

**Comment by bonham000** [comment]
Capital 'S' in middle of JavaScript.

**Comment by no-stack-dub-sack** [comment]
@bonham000 good call on these, will add them tonight
