### ISSUE TITLE
Post-Production Features

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#139]
- [ ] Pagination for Community when the total number of users exceeds what is reasonable to serve to the app in bulk.
- [ ] Modified mentorship search for the same reason (i.e. search will have to occur on server).
- [ ] Add way to update certs if user earns cert while member
- [ ] Persist FCC stats in user schema to avoid constantly fetching to FCC site. Possibly find a way to refresh periodically.
- [ ] Better integration with LinkedIn Passport API.
- [ ] D3 Global map of member geographic distribution.
- [ ] Total chat unread notifications in navbar Mess Hall link.
- [ ] Invitation system to allow membership to campers who have exemplified strong mentorship potential, but who have not earned fCC certs.
- [ ] Following/bookmark feature — [reference here](https://github.com/FCC-Alumni/alumni-network/issues/64)
- [ ] Implement global app loading state: that is, when the app loads on any route `loading === true` until we fetch everything and this prevents any sub-component from rendering (we should be able to do all this within `AppContainer`). This will help us avoid the contrived logic which exists for example in `PublicProfile` and `ChatController` right now.
- [ ] highlight search matches in mentorship search - i.e. user searches for NodeJS, we show user where that match occurred. Not doing this has already caused some confusion during beta testing : #153. 
- [ ] reporting feature, to report or "flag" users who spam with inappropriate content or harass other users. This is probably essential in Chat and, thinking in the super-long-term, could potentially even protect us from legal issues that having a live chat may open us up to. Could also be useful on profile pages in case someone adds profane / vulgar content to their profiles.
- [ ] There may be a bug with the chat notifications, where sometimes a user logs in and sees notifications for private messages when they have already read the messages and there are no new ones.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Should we open issues for each of these and label them "help wanted"? In keeping with the idea of having a release with read-identified tasks contributors can help with if they want?

**Comment by bonham000** [comment]
@no-stack-dub-sack yeah, maybe we should go through these and the other existing issues and select the ones that would be best to leave as outstanding issues for contributors to tackle.
