### ISSUE TITLE
Unfinished user verification processes break community 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#149]
If someone starts the verification process - i.e. signs in with github, but does not continue by hitting the "verify fcc data" button - the app will break. This will probably be pretty common - if someone reads our message and knows they won't get in because they don't have certs, why hit the button? They would just navigate away. 

Problem being - their user document won't get deleted from the DB though unless they hit the button and fail verification. We need to ammend this ASAP. Someone who gets distracted or who is just curious as to what the app is all about might also break the app just by getting to the verification page and not continuing.

@bonham000

**Comment by bonham000** [comment]
@no-stack-dub-sack this is closed now right?
