### ISSUE TITLE
NavLink (react-router) components in nav bar do not stay active

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#15]
Now that the `<NavBar />` component is connect to Redux, the `activeClassName` props no longer work. When the element is inspected, you can see that the `class` attribute no longer changes on click. I've looked into this, and it seems like this has been a known issue for other React-Router versions, with the `activeClassName` prop, not specifically with this component, when nested inside the component that is created when a component is connected to Redux.

This is very annoying, because it is very nice to have those active class names. Not sure if there is currently a way around this. I've tried connecting `<NavBar />`'s parent and making the decision on which nav bar (user or guest) to render there, or passing down the needed info as a prop and still deciding in the nav component, but both of these approaches actually work less and result in a non-working nav bar.

So I'm a bit stumped. Our only choice may just be to write some custom logic and CSS to show the right color when a link is active. :sob:

**Comment by bonham000** [comment]
Yeah this thing sucks I just spent a while working on trying to make it function correctly.

If you click the home route in the Nav and then re-click any other route they seem to highlight correctly.

**Comment by no-stack-dub-sack** [comment]
> If you click the home route in the Nav and then re-click any other route they seem to highlight correctly.

Well how dumb is that! Ughh...

Here's a few articles that seem to take up similar issues:
- https://github.com/ReactTraining/react-router/issues/2483
- https://github.com/ReactTraining/react-router/issues/3935
- https://github.com/ReactTraining/react-router/issues/3286

**Comment by no-stack-dub-sack** [comment]
### RESOLVED 

By wrapping `NavBar` in `Route` component

**Comment by etiennejcharles** [comment]
If anyone comes across this post - I suggest you read this. 

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#the-solution

**Comment by liamm12** [comment]
This because `activeClassName` is updating outside of redux.

You can accomplish that by setting `pure` to false

`export default connect(mapStateToProps, null , null, { pure: false })(App)`

> Note that this will make your application less performant, so only do this if you have no other option

Or you can use `withRouter` from `react-router-dom`

`import { withRouter } from 'react-router-dom';`
`export default withRouter(connect(mapStateToProps, matchDispatchToProps)(App));`
