### ISSUE TITLE
Feature request: retract a like

### ISSUE THREAD

**Issue by jboxman** [FCC-Alumni/alumni-network#154]
Many services allow a like to be retracted by clicking it again.

**Comment by bonham000** [comment]
This seems like a great thing for someone to implement post-production or whenever they want to with a PR.

**Comment by thomlom** [comment]
I can help with that issue. I have basic React & Redux skills and I think I can handle it.

**Comment by no-stack-dub-sack** [comment]
@thomlom Thanks for the offer, and sorry for the late reply, but I think I'm going to close this issue for now to clean things up a bit based on the decisions made in #158 and the recent updates to PR #207 which makes this and any other changes to chat null and void. 

Plenty of other things to do though if you have some time and feel like contributing! Do you know much about testing React by any chance?
