### ISSUE TITLE
Can't unlike mess-hall comment or private chat

### ISSUE THREAD

**Issue by Mozar10** [FCC-Alumni/alumni-network#155]
Site looks and works awesome !

This is a small issue, re-clicking the heart won't revoke (I'm tired, revoke works here right? lol) the original like.

**Comment by no-stack-dub-sack** [comment]
@Mozar10 thanks! Duly noted. We will consider this. Shouldn't be to large a leap from what we already have. I'll ask @bonham000 what he thinks. But going to close this as duplicate of #154
