### ISSUE TITLE
Indication for honorary members

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#156]
It's confusing to other users when they see someone joined why they know has no certs... we should consider some kind of modification to the user schema that would indicate honorary member

**Comment by bonham000** [comment]
We could easily show something in the UI for users who have no certs (i.e. zero certifications => derived state: `honoraryMember === true`) presuming that the only users who can have no certs are honorary members.

**Comment by no-stack-dub-sack** [comment]
@bonham000 that's pretty much exactly what I was thinking
