### ISSUE TITLE
feature request: project collaboration tab/filter/search

### ISSUE THREAD

**Issue by Matthew-Burfield** [FCC-Alumni/alumni-network#157]
The whole point of FCCAN is to be able to find meaningful collaborative relationships. I.e. mentors/mentee and to work on projects together.

The mentor/mentee part has been done well with a separate tab that allows me to search all users. However, no functionality exists to let me have that same search for projects other members are working on.

To make it easier/better to collaborate on projects, I would like to see a similar tab like there is for mentors, but for projects that users have assigned in their Collaboration section of their profile.

Would be awesome to be able to filter on projects based on tech stack, number of collaborators, number of commits, latest commit.

**Comment by no-stack-dub-sack** [comment]
@Matthew-Burfield for the record, I really really like this idea, and it's something that crossed my mind at some point that I either forgot about, or decided didn't fit into the idea we had of a true MVP at the time. 

That said, for now, I think we're going to hold on implementing this. HOWEVER, I do believe it should be implemented at some point, but I think in the interest of time, and in keeping with the MVP idea, we can hold off until after production. 

Unless you disagree @bonham000, as I think it is something that will promote better collaboration among users.

**Comment by Matthew-Burfield** [comment]
Definitely keeping the MVP as small as possible is a great idea. The quicker you can launch and get more feedback, the quicker you can iterate and get better :)

You'll quickly learn what users *really* want once you launch, and what things will keep users coming back for more.

**Comment by no-stack-dub-sack** [comment]
closing in favor of #218
