### ISSUE TITLE
public / private email 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#159]
As raised by @jdmedlock on the beta fccan slack chat: 

> So far the only question I have is is it the case that my email is viewable by others registered on the FCCAN site? If so, would it make sense to give the user the option of not sharing so the FCCAN team could use it, but not the general public. If I remove my email then I'm effectively cutting myself off from all communications - public and from FCCAN team

If I'm understanding correctly - the suggestion is to allow users to enter their email, but keep it private in case FCCAN team needs to contact them. Interesting point. 

@bonham000 This was also raised by @QuincyLarson when I demoed the app to him.

**Comment by belcurv** [comment]
Agreed that I would prefer my email remain private. What about an email form instead of visible email address? Nodemailer is really easy to work with.

**Comment by bonham000** [comment]
@no-stack-dub-sack I think this is reasonable. I mean are we going to email the members? Personally, I would rather not support a feature like that. People get enough emails. And with chat and other social media links, users have plenty of ways to try and contact each other. My view would be to just remove email entirely.

**Comment by no-stack-dub-sack** [comment]
@bonham000 before I saw your comment, I went ahead and implemented the ability to make emails private. Deploying changes now based on PR #164. I think this may be useful if we want to send emails in the future, for whatever reason. 

Awesome ML mentorship matching engine anyone???

**Comment by no-stack-dub-sack** [comment]
@bonham000 closing this for now
