### ISSUE TITLE
Suggestion: don't link coding profile skills to wikipedia

### ISSUE THREAD

**Issue by Matthew-Burfield** [FCC-Alumni/alumni-network#162]
Currently clicking on the skill buttons in the Coding Profile section of someone's profiles links you to the wikipedia page which isn't very helpful. Especially things for "React-Router" as the wiki page doesn't even exist.

My suggestion would be to link you to the mentor page within the FCCAN with that particular skill selected in the filter, so you can quickly find other users that also have that same skill

**Comment by bonham000** [comment]
This is a great idea!

**Comment by no-stack-dub-sack** [comment]
@Matthew-Burfield really awesome idea! I agree this is wayyyy better! Thanks for the insight.

**Comment by no-stack-dub-sack** [comment]
@Matthew-Burfield done! in PR #171 

redeploying shortly and changes will be available by later tonight
