### ISSUE TITLE
Android Firefox input/select/text area issues

### ISSUE THREAD

**Issue by belcurv** [FCC-Alumni/alumni-network#165]
Specifically Android 4.4.4, Firefox app ver 53.0.1

**Profile > Preferences**

1. I cannot select mentor skills from the drop-down skill picker
2. I cannot input text into the **Bio** text area
3. The **Bio** text area has no overflow / scroll bar, and the place holder text gets cut off.

Firefox:
![Firefox issues](https://cloud.githubusercontent.com/assets/17347977/25931837/64aa5f62-35d4-11e7-8312-35aefc381f90.png)

Chrome works:
![Chrome works](https://cloud.githubusercontent.com/assets/17347977/25931828/5087a184-35d4-11e7-861c-834e01580cf8.png)

**Comment by no-stack-dub-sack** [comment]
@belcurv Thanks for opening this. Not even sure where to begin on solving this unfortunately. Will have to leave this one open for the time being.

**Comment by smiller171** [comment]
Why on Earth are you running an Android version from 2013?

**Comment by belcurv** [comment]
It has its uses. KitKat still has [nearly 19% android market share](https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/).

**Comment by smiller171** [comment]
@belcurv While that's true, I'd hazard a guess that most of those are appliances and phones for very basic users. It's really uncommon to see software that old on tools used by developers, and this site isn't targeting a mass market audience.

My point is, while I'd expect Facebook to need to support a 4 year old mobile OS, I wouldn't expect a developer network to need to. It surprises me that this was found at all, much less before it was officially released.

**Comment by belcurv** [comment]
@no-stack-dub-sack - @smiller171 is likely right. Feel free to close at your convenience given low/zero applicability to target audience.

**Comment by smiller171** [comment]
@belcurv Were you just testing for the sake of it, or is this actually a device you use? Genuinely curious.

**Comment by belcurv** [comment]
@smiller171 - orig Moto X. Genuinely use it. Perfect handset for me.

**Comment by no-stack-dub-sack** [comment]
@belcurv haha, ok, I'll close for now. I didn't even notice the old version of android you were using, though I did notice that I wasn't experiencing the same issues. Will close for now unless this comes up on newer platforms.

**Comment by smiller171** [comment]
@belcurv Yeah, the OG Moto X was amazing. My wife and I both had them, but time was not friendly to them and they had to be replaced. Both using Pixel now. In most ways the Pixel is better, but that curved soft touch back is missed.

**Comment by belcurv** [comment]
@smiller171 - mine is mostly physically ok. The usb connector has gotten pretty loose but it still charges, etc without issue. I'll miss it when it dies, but I'm looking forward to a handset with a **much** better camera and fingerprint reader. Pixel is definitely on my shortlist. Nexus 5x factory refurbs are often on swappa for ~$200-$250 and look like a good value as well.

**Comment by smiller171** [comment]
@belcurv If you can make it to the fall the 2nd gen Pixel will drop so you can get the latest, or get good sales on the Pixel.

It was internal components that were degrading on our Moto Xs. Screen burn was really bad, and electronics were degrading to the point that my wife's phone would randomly reboot and spend an hour optimizing before it would come back on.

Getting off topic though.
