### ISSUE TITLE
Deleting a private chat message doesn't remove the associated notification

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#176]
If you are private chatting someone and you message them and then delete the message, they will still have a notification for that message. Basically, we want to decrement the notifications if a message is deleted.

The flow could operate the same as with the other chat operations which handle deleting a message. We simply want to additionally decrement the notifications (if they exist) when we update the database in step 1, and then update them for the actual user (for the real-time update) in step 2.

**Comment by gwenf** [comment]
Is this still going to be worked on if you are going to use an embedded gitter solution for chat?

**Comment by no-stack-dub-sack** [comment]
@gwenf sorry, didn't see your original message. I just came here to close this for now based on #158 and #207. Will reopen down the line if for some reason those efforts are abandoned.
