### ISSUE TITLE
limit chat message length

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#185]
During beta, someone tested this by plopping in an egregiously long message. Seems like something we should put some kind of reasonable limit on. Open to suggestions. Should be easy enough to implement.

**Comment by bonham000** [comment]
Did you do this @no-stack-dub-sack ?

**Comment by no-stack-dub-sack** [comment]
closing this for now based on #158 and #207. Will reopen later if efforts are for some reason abandoned.
