### ISSUE TITLE
alphabetize imports, props, prop-types, etc. throughout codebase

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#186]
@bonham000 I think that as this project gets bigger and gains more contributors, this could be valuable. 

I've created a branch to get started on this, but am making slow progress and this is low priority. 

I've tried to configure ESLint to catch these errors, but have only managed to do it per file with config comments. In order to do this globally, I believe we'd need to eject from CRA. Which clearly, is not worth it. 

The larger point is that I think we need to enforce something across the board so things aren't just willy-nilly, and the codebase maintains some kind of consistency (especially if people actually start contributing). But I think asking people to "pyramid" their imports and such somehow seems silly and less professional. 

Also, when I was working on the refactor of `Preferences` the other day, I had alphabetized the imports and it was a big help when I was looking for specific packages in the list, so I see the practicality as being more valuable than the aesthetics of our current convention (even though I can't reiterate enough how much I like the way it looks).

**Comment by bonham000** [comment]
@no-stack-dub-sack yeah, I agree with this as well. I guess it essentially goes with the 'style guide' Issue to establish more standard practices for the styles. Getting it setup with esLint rules and some automated check would be pretty neat too.
