### ISSUE TITLE
Add a better Readme

### ISSUE THREAD

**Issue by theodesp** [FCC-Alumni/alumni-network#188]
The Readme is the first thing someone reads when visiting the page and its currently too bare and with no helpful information like app features, screenshots. Also some links are wrong for example the contributing guideline points to the edit page.

We need a presentable Readme with links to FCC resources and a plan to give directions on how to install and use the app.

Any other improvements should be noted here in this ticket

**Comment by no-stack-dub-sack** [comment]
@theodesp fixed the link to contributing.md, thanks for pointing that out. That doc does have pretty thorough resources for installing and running the app. However, this is not official FCC so linking to official FCC resources may not be fully appropriate, though much of the material is based off of theirs.

Your other comments about screenshots, etc. are fair and we can def do something there. Interested in taking that on?

**Comment by theodesp** [comment]
I would love to collaborate on the project. I just need to plan my time with a full-time job, a family, mentoring and a side project. Most probably I will do some pull requests from the Post-Production Features

**Comment by no-stack-dub-sack** [comment]
Sounds good! I totally understand. 

If you want to work on something, just leave a comment on the issue and @mention myself or @bonham000. Thanks again!

**Comment by jamesjpk123** [comment]
https://fcc-alumni.com/images/fcc_high_five_logo.svg could be added to the top of the readme. I'm not sure if that is the alumni "logo" or if https://fcc-alumni.com/images/fcc_hands_in_logo.svg is. Either way, there should be a logo in the readme.md.

**Comment by no-stack-dub-sack** [comment]
@jamesjpk123 the high five one is the main one we're using. Do you want to add this in?

**Comment by jamesjpk123** [comment]
I can add that in later @no-stack-dub-stack, I'll use the high five one.

**Comment by jamesjpk123** [comment]
@no-stack-dub-sack not stack xD

**Comment by stephenjfox** [comment]
@jamesjpk123 Any update on the progress of the README?

**Comment by jamesjpk123** [comment]
Oh totally forgot about this! Will totally work on the read me once I get back from a trip this weekend. Thanks!

**Comment by jamesjpk123** [comment]
Ok finally found enough time to add it in, will add in the next 10 mins @stephenjfox.

**Comment by jamesjpk123** [comment]
#251 is a pull-request I created to fix the image issue.

**Comment by jamesjpk123** [comment]
#258 is a second pull request, that is a copy of the first but done in one commit.
