### ISSUE TITLE
User authentication issue

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#19]
When user is logged in, on Dashboard page, and they attempt to reload, app redirects to login via the HOC even though they should still be logged in, state from redux store does not persist on reload. I think we need to reset the redux state on componentDidMount() in Dashboard.js or something? Any ideas?

**Comment by bonham000** [comment]
Can we use local storage?

**Comment by no-stack-dub-sack** [comment]
probably, I should have thought of that

**Comment by bonham000** [comment]
Use in some way to persist a user is logged in. I can look at this too in a bit.

**Comment by Bigghead** [comment]
I wonder why the Redux doesn't persist upon reload.Could we check if the user is still logged in, on the server, after refreshing the dashboard?

**Comment by no-stack-dub-sack** [comment]
@Bigghead we could, but probably inefficient compared to other ways we can do it I think.

**Comment by Bigghead** [comment]
In one of my pet projects that uses sessions and oAuth,for some reason, after logging in, if I refresh a page, the user would get logged out. Still can't track that down. 

Maybe it's the same problem here

**Comment by Bigghead** [comment]
Actually, nvm. I dont quite get the inner dealings of Redux. It might be something completely different

**Comment by no-stack-dub-sack** [comment]
No it may be similar, and actually I think you're right, either way we'll need to ping the server to reset the state, but first we need to get the page to not redirect without any state being present, so local storage seems like a good option. I got the page to reload using it, but for some reason having trouble making the call to the server and resetting the state

**Comment by bonham000** [comment]
Redux is all JavaScript, page reload returns to initial store state.

You will have to either maintain auth data in local storage or make a server request (this is what I did in the PR just now). Curious about session expiration. Looks like we can set a max age for Passport session [something like this](http://stackoverflow.com/questions/17991050/how-to-set-the-session-timeout-after-log-in-passportjs).

**Comment by bonham000** [comment]
I'm going to close this.
