### ISSUE TITLE
rethink hosting (move from Heroku to AWS?)

### ISSUE THREAD

**Issue by ooade** [FCC-Alumni/alumni-network#190]

**Comment by theodesp** [comment]
I think this is critical as there is oath requests happening for login and GitHub integration, private messages etc.

**Comment by no-stack-dub-sack** [comment]
@ooade @theodespI believe that the github oath requests are still happening over HTTPS because it actually redirects to GH for that. 

The reason this is the case now is because with a custom domain on heroku, serving over HTTPS is quite expensive. This one will have to be revisited and discussed at greater length. @bonham000 any thoughts?

**Comment by ooade** [comment]
@no-stack-dub-sack You can serve https via cloudflare??

**Comment by gwenf** [comment]
@no-stack-dub-sack what about hosting on AWS and getting a free ssl?

Hosting could be almost free for the first year if you use a T2 Micro on EC2.

**Comment by no-stack-dub-sack** [comment]
@gwenf this sounds viable - I know virtually nothing about AWS so maybe you'd be willing to provide some guidance? A year is a good trial period, I think long before then we will know if the app is worth continuing to host at a cost.

**Comment by gwenf** [comment]
So, the SSL would be free. Amazon just makes you pay for any other paid resources that you use. They also have a free tier for the first year where you can use quite a few of their services for free up to certain levels (which are pretty generous).

Take a look at the EC2 service and see if you think it would work for you: https://aws.amazon.com/ec2/instance-types/

AWS has pretty good pricing. I host several applications, databases, bots, and other serverless stuff on there and I still don't think I've paid over $10 in a month. It's cheaper than Heroku and you have more options but it can be a little bit harder to set up vs `heroku push`.

https://aws.amazon.com/certificate-manager/pricing/

**Comment by smiller171** [comment]
I'd also be willing to help you move to AWS. I'm a DevOps Engineer by day, working primarily in AWS. Could get you moved from Heroku to AWS in no time at all, with the ability to scale if you wanted it. Are you currently running the backend and frontend on a single server?

**Comment by smiller171** [comment]
Also as was pointed out by @ooade, you could get free SSL just by putting the site behind CloudFlare

**Comment by no-stack-dub-sack** [comment]
@gwenf Thanks for the info, I'll have to check this out!

@smiller171 I'd gladly take you up on this offer. Maybe we can find some time to pair this week?

I love it! The FCCAN already at work sparking some collaboration and mentorship (which I could desperately use on ops related issues)! That makes me very happy.

**Comment by smiller171** [comment]
@no-stack-dub-sack You can find me on Gitter, Keybase, or email if you wanna chat. Or let me know if something else works better for you.

**Comment by no-stack-dub-sack** [comment]
Thanks @smiller171 for helping to get us up and running on CloudFlare! The site is now secure! 

Leaving this open but changing the title since we may still want to look at how the site is hosted for a more permanent and robust solution.

**Comment by smiller171** [comment]
reminder that you need to get some of your paths fixed so that they point to https instead of http addresses to avoid mixed content warnings.

**Comment by no-stack-dub-sack** [comment]
closing for now... until FCCAN picks up more steam, I think we're comfortable with the current setup.
