### ISSUE TITLE
Issue with adding/deleting custom skills & interests

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#195]
I spent some time working on this before actually unleashing this, and thought I had it down, but experiencing some difficulties. It looks like when some entries are rejected, a blank tag gets shown in the user facing profile. And also having trouble deleting skills/interests after something happens. Haven't investigated as I'm at work, but I've noticed the issue and will work on troubleshooting later.

**Comment by smiller171** [comment]
I tried adding a custom skill, and now I can't add any skills at all.

**Comment by smiller171** [comment]
Your hint about the blank tag helped. After deleting it I can add stuff again.

**Comment by smiller171** [comment]
Looks like there's an issue in Preferences.js trying to do a toLowerCase when you try to submit a custom skill.

![screen shot 2017-06-26 at 10 56 39 am](https://user-images.githubusercontent.com/3587913/27545590-2e638240-5a5e-11e7-91db-0dc9307037ad.png)

**Comment by no-stack-dub-sack** [comment]
@smiller171 sweet, thanks for giving me a head start on this! I hadn't even gotten that far yet as looking at the errors being at work and all. This keeps sucking me back in though! 

I should be able to fix this tonight.

**Comment by smiller171** [comment]
@no-stack-dub-sack I'm not sure I'm actually on the right track with that error, I think that's something else. After more testing that error only comes up when I try to enter the same skill multiple times (because the first is hidden) It seems to fail silently on initial add.

**Comment by smiller171** [comment]
however, if I enter one custom one which becomes empty, and then another custom one, it appears. However after this I can't use backspace to delete. Possible this is an issue of pointing at the wrong location in an array?

**Comment by smiller171** [comment]
I think I found the issue, but I'm not certain.

https://github.com/FCC-Alumni/alumni-network/blob/0fffcd7fc4e5e74d8fc69fba0044d42fc4bb9dc4/client/src/components/dashboard/Preferences.js#L119-L129

Currently the code is this:
```javascript
  handleSkillsChange = (e, { value }) => {
    /* extra logic here and in sister function
    to make sure same skills with different cases
    are not added to the list */
    var { user } = this.state;
    user.skillsAndInterests.coreSkills = value
      .map(el => el.toLowerCase())
      .filter((el, idx, arr) => arr.indexOf(el) === idx)
      .map(el => SKILLS_MAP[el]);
    this.setState({ user });
  }
```

I think there's a concurrency issue here:
```javascript
    user.skillsAndInterests.coreSkills = value
      .map(el => el.toLowerCase())
      .filter((el, idx, arr) => arr.indexOf(el) === idx)
      .map(el => SKILLS_MAP[el]);
    this.setState({ user });
```
I believe it's setting the state before `user.skillsAndInterests.coreSkills` is reassigned as `value`

![screen shot 2017-06-26 at 3 30 46 pm](https://user-images.githubusercontent.com/3587913/27556668-79db3f80-5a84-11e7-8b72-a7d2a53929fc.png)

As you can see, `value[4]` is "ansible", but `user.skillsAndInterests.coreSkills[4]` is undefined.

The same applies for interests.

**Comment by no-stack-dub-sack** [comment]
@smiller171 So what I think was going on was that before I left for vacation (just got back) I did some tinkering with this code, and probably didn't test it thoroughly enough. I was trying to prevent someone from adding "javascript" when "JavaScript" was already on the list. But that caused problems when a user tried to add a skill, because the hard coded `SKILLS_MAP` wouldn't have that new skill. So every time `handleSkillsChange` was running with an added skill, `null` was getting added to the array. There does also seem to be some funky concurrency issues going on between the 2 functions (`handleSkillsChange`, `handleAddSkill`) but I think they can be avoided with the update I am about to push which now seems to do what I wanted it to do originally -

- no matter the case, if the skill is already in the dropdown, it will map to the correctly cased option
- if skill is not in dropdown, it will add to the list in whichever case the user entered it. Duplicates will not be allowed from there (e.g. if user adds `ansible`, `Ansible` will not be added to the list if that is attempted).

I believe this all works now, and now I just need to go through and delete the `null`s from the user objects that contain them for skills or interests. In all of the above "skills" and "interests" are interchangeable.

**Comment by smiller171** [comment]
Nice work @no-stack-dub-sack. Let me know when this is pushed to prod and I'll run it through its paces.
