### ISSUE TITLE
Callback error after Logging in with Github

### ISSUE THREAD

**Issue by lespinalrivera** [FCC-Alumni/alumni-network#196]
I was Logging in with my github account and after the oauth page, the callback gave me an internal server error. (Tried twice).

![image](https://user-images.githubusercontent.com/18403282/27546186-eb6fa570-5a46-11e7-9f4d-5b25861eeb3f.png)

**Comment by no-stack-dub-sack** [comment]
@lespinalrivera hmmm, interesting. That should not be happening on the prod site. And many others are able to log in fine. Can you provide more details about what might make this situation unique?

Was this just now? And can you try again just for kicks?

@bonham000 any ideas here?

**Comment by lespinalrivera** [comment]
@no-stack-dub-sack and @bonham000 It seems that after 5 tries, It allowed me to sign in!

I don't know if this is good or bad :joy: as I cannot replicate the error now.

One thing I did noticed is that the 5th time I tried it gave me a different callback code from the previous ones.

### Since It cannot be replicated again, this issue can be closed.

**Comment by no-stack-dub-sack** [comment]
@lespinalrivera Ok, cool. Thanks for the feedback. I will close for now and will look for similar reports along the way. That's def odd that this happened. 

Thanks again and glad you were able to sign in!
