### ISSUE TITLE
Add Feature to include local meetup groups

### ISSUE THREAD

**Issue by briancbarrow** [FCC-Alumni/alumni-network#198]
Would be great to see if anybody near you in local meetup groups are on here. Could incorporate the Meetup API

**Comment by no-stack-dub-sack** [comment]
@briancbarrow That's a pretty cool idea - can you link to the API docs? I am unfamiliar

**Comment by briancbarrow** [comment]
https://www.meetup.com/meetup_api/

**Comment by gwenf** [comment]
We could have the option in someone's profile to connect their meetup or enter what local FCC meetup or FB group they are part of. We could add this feature to the filtering options too.

**Comment by no-stack-dub-sack** [comment]
This is a great idea, and one I will keep on the backburner, but activity has been slow overall... I'd like to see if this thing picks up any speed before going feature crazy! 

@briancbarrow @gwenf it's a bit hard to measure whether or not people have visited the site lately, or actually used it (that's harder), for my own personal edification, have either of you been back here or formed any relationships (reached out to people or had them reach out to you) via the app?

Just trying to get an idea from average users if its actually adding any value. Also open to any suggestions on how to more effectively measure this. Starting to wish we asked for email addresses at sign up so we could message things to people and send out surveys... oh well. Thanks!

**Comment by no-stack-dub-sack** [comment]
closing for now but added to ☝️
