### ISSUE TITLE
Tone down LinkedIn permissions

### ISSUE THREAD

**Issue by patricksevat** [FCC-Alumni/alumni-network#200]
Hi all,

First of all great job creating this site and community!

I wanted to link my LinkedIn profile but I find your requested permissions a bit bold ;)

I'd argue that the first two permissions are more than enough.

Also it might be more professional to create a company\community(?) profile for FCC Alumni and route authentication through that profile rather than Peter's profile

```
YOUR PROFILE OVERVIEW
Name, photo, headline, and current positions
YOUR EMAIL ADDRESS
The primary email address you use for your LinkedIn account
SHARE, COMMENT & LIKE
Post updates, make comments and like posts as you
COMPANY PAGES
Manage your company page and post updates
```

**Comment by no-stack-dub-sack** [comment]
@patricksevat Thanks for the comment! To address your concern - we have no control over this, these are the permissions linkedin's API automatically provides for this level of integration. 

On your second point - that is totally valid, and I forgot that we hadn't updated this. I will do this very soon. 

Overall, it should be noted that the LinkedIn integration is rather weak. Unfortunately, using PassportJS, with this level of access, the API does not give us access to users' profile URL (if we were using LI for sign-in it would, be we only want to use it for this. There doesn't seem to be an easy way to have the best of both worlds, so at this point all it does is pull in your name exactly as it appears on LinkedIn - when a user clicks the LI link, it will run a query against that name. If it is a common name, e.g. John Smith, this is virtually useless. 

We would like to add better integration and is on our todo list.

**Comment by patricksevat** [comment]
Thanks for the reply, I'm not sure exactly which type of Passport implementation you use, but I have run into this issue for a personal project as well. I wanted a JWT based auth and Passport did not support this for LinkedIn. I ended up writing my own LinkedIn token auth.

The core of it is that I redirect back-end to LinkedIn Auth endpoint at which I can define the permissions I require. You can find most of it [here](https://bitbucket.org/PatrickSevat/poldocs/src/5a7c46a1899c51c440a321f52506d091ffcdd256/server/api/auth/linkedIn.js?at=elasticAndDBadjustments&fileviewer=file-view-default). Perhaps it helps. I'll take a look at your Auth system this weekend (if I have some time) to see if I can clone my system into a PR for your project

**Comment by no-stack-dub-sack** [comment]
@patricksevat sounds great! Let me know what you come up with. I'll take a look at this when I have a few minutes. Working now on updating the company page.

**Comment by no-stack-dub-sack** [comment]
@patricksevat I've fixed the auth page so that you see FCCAN instead of my profile. Thanks for the reminder on this.

**Comment by no-stack-dub-sack** [comment]
@patricksevat closing this as stale for now since we cannot explicitly control these permissions. If you get around to it, I'd be interested in seeing what you worked up when you had a similar issue. Another note I forgot about earlier is that there is a pop-up that does say we don't use this info for anything... so hopefully that will let people know this is default and just used to sign in.
