### ISSUE TITLE
APP IS DOWN

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#201]
trying to fix

**Comment by smiller171** [comment]
already back up for me?

todo: add status page :)

**Comment by no-stack-dub-sack** [comment]
Ughh. Yes. I'm not sure what's causing this. It has something to do with a user trying to sign up, but Heroku seems to be recovering quickly-ish.

**Comment by smiller171** [comment]
Using too much compute or RAM?

**Comment by no-stack-dub-sack** [comment]
I don't think so - the error happened when a user was trying to process verification. It looks like they joined, then deleted their account, then tried to join again. That shouldn't be an issue though. I'm having trouble accurately decoding the logs.

**Comment by smiller171** [comment]
but it brought down the whole app? Or false alarm and just one user had issues?

**Comment by gwenf** [comment]
It was down off an on yesterday. Are you on the free Heroku account?
If you are on the free tier, the app shuts down for a certain amount of time ever day I think.
