### ISSUE TITLE
Add Donation Link

### ISSUE THREAD

**Issue by smiller171** [FCC-Alumni/alumni-network#205]
Whether it's Paypal, BTC, ETH, or whatever, you should put up a way for people to help with hosting costs.

**Comment by no-stack-dub-sack** [comment]
@smiller171 hmmm - I'm hesitant to do this since we're not officially a non-profit or affiliated with FCC - this would open us up to scrutiny over what's happening with the money. Of course nothing dishonest would happen with it, but I don't know if there are potential legal ramifications or anything like that. If there's a solid established precedent, I'd be open to it.

**Comment by smiller171** [comment]
@no-stack-dub-sack There's a pretty established precedent for open source developers to leave up a PayPal email and/or Bitcoin address to support development. Often with a message like, "Like what I'm doing? Buy me a beer!" or "Donations help keep this site running"

AFAIK as long as you aren't making specific claims about how the money is spent, you aren't opening yourself up to any legal liability (other than taxes) and there's a general consensus that developers deserve to be compensated for their time even in the open source space, so people don't care if you're using that money to buy whiskey and hookers so long as the service keeps working well.

One thing I've seen that's really cool is when there's excess donation money coming in sometimes a system is set up that automatically tips developers for pull requests that get accepted. I got a couple Primecoin this way from the Ansible project.

**Comment by gwenf** [comment]
I think this is a good idea in the near future.

It could help if you are transparent about the costs of hosting and running this app.

**Comment by smiller171** [comment]
@gwenf currently labor is a much greater expense than hosting since it's running on Heroku's free tier

**Comment by gwenf** [comment]
Yes, but it will soon outgrow the free tier I think. Although the next tier is only $7 per month.

**Comment by smiller171** [comment]
@gwenf I'm hoping to help @no-stack-dub-sack get off Heroku into AWS. As long as the backend load isn't severe, it should be able to scale up significantly before costing anything, with better performance.

**Comment by no-stack-dub-sack** [comment]
@smiller171 Yup, I'm still game to continue this conversation after the holiday.

**Comment by jamesjpk123** [comment]
If you said, "Like what I do? Buy me a beer" would be totally different than "Donations help keep this site running". I would personally make it the "Like what I do" line. It lets you use the money for hosting costs, and for rewarding your work! You could just put a tagline underneath the donation line saying "The FCC-Alumni Network is not affiliated with freeCodeCamp. If you want to donate to them, click here." or something like that. Or even better, get affiliated with FCC so you could get donation money from them, to help with the network! It would make it way less complicated!

**Comment by smiller171** [comment]
@jamesjpk123 IMHO a paycheck helps keep someone interested in putting the effort in to keep the thing running, but I'm probably splitting hairs.

**Comment by no-stack-dub-sack** [comment]
@smiller171 @jamesjpk123 Thanks guys, I'm going to close this for now though. Hasn't been a whole lot of activity here as of late, so I think I'm at the point where I would not consider this for now. If FCCAN ever blows up, you never know! Don't forget to tell your friends so that could actually become a reality 😄
