### ISSUE TITLE
Fix session timeout

### ISSUE THREAD

**Issue by smiller171** [FCC-Alumni/alumni-network#211]
If possible, FCC-Alumni should not make me click the "log in" button again if I still have an active GitHub session. FCC-Alumni is logging me out much too frequently, but it immediately logs me back in because my GitHub session is still good.

**Comment by no-stack-dub-sack** [comment]
@smiller171 how frequently is that happening? It will keep mine logged in for quite a while. Unless you mean if you actually leave the page. I think once you leave it will require you to log back in. 

@bonham000 can you weigh in on this at all?

**Comment by bonham000** [comment]
@no-stack-dub-sack yes I think the passport session we set up should give the user 8 hours before expiring their session (see `passport.js` file for the server), but if Heroku drops the app because of overall inactivity the session will be ended for that reason, which could be before 8 hours.

**Comment by smiller171** [comment]
@no-stack-dub-sack @bonham000 What I mean is, after that timeout (Which is much much longer than GitHub's own Timeout) I have to click "log in" again, but it verifies my cached credentials instantly when I do. If there is no user interaction of entering a password required, you should automatically check those credentials without bugging the user, and only notify the user that they need to reauthenticate if there is some interaction required by them like re-entering their password.

**Comment by no-stack-dub-sack** [comment]
@smiller171 to make sure I follow this, you're just saying, if the credentials are cached anyway, then we shouldn't even require the user to hit login, right? We should just detect when the credentials are cached and bring them right to the site if so. Am I following correctly?

**Comment by bonham000** [comment]
@no-stack-dub-sack I think he means just automatically try to login the user (e.g. when they visit `fcc-alumni.com`). Is that right @smiller171?

**Comment by no-stack-dub-sack** [comment]
@bonham000 that's also what I was trying to say in my perhaps a little convoluted comment. Automatically log the user in if their credentials are still cached.

**Comment by smiller171** [comment]
@no-stack-dub-sack Yes, that's what I'm saying. Basically attempt to authenticate in the background. If they have authenticated before and there is an active GH session it should work and you don't have to bug the user. If the background authentication fails then you ask the user to log in again.
