### ISSUE TITLE
Profile not updating cert info / Add "Refresh Certifications" Button

### ISSUE THREAD

**Issue by chdanish** [FCC-Alumni/alumni-network#217]
User profile are not auto updating as I have completed "Data Visualization Certification" after I signup "www.fcc-alumni.com" but my profile only showing "Front End Certification" which I completed before signUp.

**Comment by smiller171** [comment]
@no-stack-dub-sack Probably need to implement a "refresh" button, and/or automatically check for updates to dynamic values any time someone visits a user's public profile or their own profile settings. I may be able to take a look at the code and take a shot at implementing this.

**Comment by no-stack-dub-sack** [comment]
@chdanish @smiller171 Yes, this is a known issue, we may have added this to post-production features issue. 

@smiller171 that would be awesome, if you want to take a shot at this, by all means! I think maybe the best thing to do is just like you said - in the preferences Certifications section, just have a "Refresh Certs" button. Much of the code for implementing this already exists, it's just connecting everything in the right away I should think. 

I'll refrain from adding a "help wanted" label for now since you've expressed an interest @smiller171, but if for some reason you're unable to get to it, just let me know!

**Comment by chdanish** [comment]
@no-stack-dub-sack Thanks bro! very happy to achieve 2nd milestone.I know very little of nodejs  for now otherwise would have try to contribute.

**Comment by smiller171** [comment]
@chdanish typically you wouldn't close an issue until it has been fully resolved and deployed. At this time we've only agreed to look at the issue, it hasn't yet been fixed.

@no-stack-dub-sack could you assign this to me in the GitHub UI?

**Comment by smiller171** [comment]
@no-stack-dub-sack also, are you opposed to having it auto-check when someone pulls up their profile if I can get it working?

**Comment by smiller171** [comment]
@no-stack-dub-sack could you re-open this, or should I re-open in a new issue? I don't have permission to reopen the issue myself

**Comment by no-stack-dub-sack** [comment]
@smiller171 reopen. 

Auto-check at which point? When they login or when they pull up their Preferences page?

I think autocheck in an ideal world is better, but that also could mean that we're creating a lot of "fake" traffic for FCC if this app ever takes off, essentially by simulating visits that aren't real users. This was a concern brought up by @bonham000 when we were working on the Public Profile page which also visits FCC endpoints to get it's info. We whittled that down to once per visit, then store the data in Redux. So if we can keep it to a minimum it should be fine I guess, we should just keep it in mind going forward that if we ever really get a lot of users, moving away from auto-checking might be important.

**Comment by smiller171** [comment]
@no-stack-dub-sack It shouldn't be enough traffic to impact their load, but it could mess with analytics. You could talk with the folks at FCC to ask if you could use a query parameter or pass a header that they can filter in their analytics, or if they care at all.

I was thinking about checking whenever someone's profile is visited, but perhaps you could put a timer on it so it only checks if it's beyond a certain stale age, or if you manually hit a refresh button

**Comment by no-stack-dub-sack** [comment]
@smiller171 I'll leave that up to you, just wanted to mention the concerns we'd had on that in the past. Perhaps we can just check once per session - we can put an indicator in the redux store, e.g. `certsRefreshed` - mark it as true the first time the profile is visited during that session, if it's true, we don't check on subsequent visits.

**Comment by smiller171** [comment]
@no-stack-dub-sack That doesn't help if many users are looking at the same profile. I was thinking of handling on the backend with a last_checked timestamp in Mongo. Each time someone loads that profile the backend checks how stale the info is for that user and refreshes if it's been longer than some predetermined period of time. Perhaps a default of 6 hours configurable with an environment variable.

**Comment by no-stack-dub-sack** [comment]
@smiller171 that sounds good too. I had been thinking only do it when the user who got the new cert logs in, but this makes more sense prop.

**Comment by no-stack-dub-sack** [comment]
Anyone else want to take this on? :smile:

**Comment by nirmalmarian** [comment]
Is this still open? Sorry i am a bit late.
