### ISSUE TITLE
add all users to gitter channel before redeploying with Gitter embed 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#225]
or maybe right after. I am going to hold off on redeploying until I have time to do this.

**Comment by smiller171** [comment]
@no-stack-dub-sack since adding users to the Gitter channel currently must be a manual process, it seems to make more sense to use a public channel. Making a user wait to get access to chat does not seem ideal

**Comment by no-stack-dub-sack** [comment]
@smiller171 https://gitter.im/fcc-alumni/MessHall and https://gitter.im/fcc-alumni/Contributors are both public, however, as a sort of way to message the change, I'm still going to add everyone to the room manually since otherwise they will not find out until they log in again. So if they regularly use Gitter, they will be notified. New users will be free to discover it on their own, though.

**Comment by no-stack-dub-sack** [comment]
### done. \#exhasting
