### ISSUE TITLE
remove chat infrastructure from app

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#226]
now that gitter is embedded (see #207), all remaining chat infrastructure/code needs to be deleted. I already have a branch for this, but it may have mass conflicts and I'll prob need to redo it all. 

Going to wait a few days till we're 100 million percent sure because there's no going back once its all removed (its a lot to get rid of).

**Comment by smiller171** [comment]
@no-stack-dub-sack wasn't this fixed by #247?

**Comment by no-stack-dub-sack** [comment]
@smiller171 yup - just came here to close this. forgot to put the closing line in my PR. Thanks.
