### ISSUE TITLE
Flash Messages Stacked

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#24]
If user events create multiple flash messages in UI, they all get stacked. Should probably auto-clear old messages.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Yes, I'll assign this to myself. I actually noticed that the first time I implemented this, and added a fix in that app, but not sure if it's the best one. I'll revisit this and make sure it's fixed. 

Thinking back, it is actually designed for messages to stack, but it shouldn't stack the same one twice, but it might be good to have different messages stack, in case somehow a user causes two errors, or two messages, right after one another (as things get more complex). If a message just replaces the prior one, it's possible they may miss something. Thoughts on this?

But I did notice that that when you get booted off a protected route twice in a row, you'll see both.

**Comment by bonham000** [comment]
Semi-fixed to clear on route transitions... could be improved.

**Comment by bonham000** [comment]
Seems we still need a better solution for this guy?

**Comment by bonham000** [comment]
Also may be good to dig around and find any calls we're making to the server and make sure they are guarded with error catching that we can use to dispatch a flash message with.

**Comment by bonham000** [comment]
In the end, we can also change some flash messages to console warnings or errors, some of those that are more intended for our own debugging that is

**Comment by no-stack-dub-sack** [comment]
@bonham000 Just saw most of these messages, whoops. I know at least of a couple of server calls that have error catching and flash messages to accompany. The main call in AppContainer is.

This screen cast addresses the separate issue of margins on flash messages and page content changing at mobile UI sizes and when flash messages are cleared: 

http://recordit.co/UX14sOYo9z

Per original issue - flash messages still stack, but sometimes 2 errors occur at once... so... 
I still think maybe the best solution to cover a couple of edge cases is maybe allowing only one message at once no matter what, and auto clearing messages after an indeterminate number of seconds using a timeout. Can we revisit this maybe?

The comment in this screenshot addresses one of those edge cases (from Account.js - will be PRd shortly as of this post):
![image](https://cloud.githubusercontent.com/assets/18563015/25113222/1b2b6ace-23c4-11e7-9db9-75344b5523c6.png)

**Comment by bonham000** [comment]
This can be tentatively closed now?

**Comment by no-stack-dub-sack** [comment]
@bonham000 Yup! And I will have to remove the comment in the above screenshot in next PR as this is now fixed
