### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by MiloATH** [FCC-Alumni/alumni-network#245]
Hi,
   Does this project have a license? Most of the FreeCodeCamp stuff uses the [BSD 3-clause license](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/LICENSE.md).

**Comment by smiller171** [comment]
@no-stack-dub-sack This is your call, and a good decision to make. I like BSD-3, MIT, and GPLv3. MIT is "do whatever you want", BSD-3 is "Do whatever you want but don't use the same name", and GPLv3 is "This must stay Open Source forever. You can't use it in commercial code"

https://choosealicense.com/

**Comment by bonham000** [comment]
@no-stack-dub-sack for the React challenges we literally copied over the `BSD-3` license from the FCC repo.

**Comment by no-stack-dub-sack** [comment]
@MiloATH good call! Thought of this a long time ago and then completely forgot.

@smiller171 @bonham000 I'm familiar and happy with the language and purpose of the BSD 3-Clause license. I might choose GPLv3 if I thought this code could ever possibly be used in a very serious way, but I highly doubt that (in fact, I'm sure of it - there's nothing new here). I've just added the license and am closing the issue. Thanks @MiloATH!
