### ISSUE TITLE
Front page issue!

### ISSUE THREAD

**Issue by jamesjpk123** [FCC-Alumni/alumni-network#252]
On the front page, underneath "Welcome to the freeCodeCamp Alumni Network", it has a grammatical error! It says "An extension ofF the freeCodeCamp community" instead of what it should say: "An extension of the freeCodeCamp community".

**Comment by no-stack-dub-sack** [comment]
@jamesjpk123 Nice catch! If you want, when you go to squash your commits for your other PR, you can add this fix in there as well?

**Comment by jamesjpk123** [comment]
Sure!

**Comment by no-stack-dub-sack** [comment]
Cool, thanks!

**Comment by jamesjpk123** [comment]
@no-stack-dub-sack, I am a new contributor to this repo. What file path would I go through to get to the content of the home page?

**Comment by jamesjpk123** [comment]
Ok, this pull request finishes the job: #257 @no-stack-dub-sack

**Comment by smiller171** [comment]
fixed by #257
