### ISSUE TITLE
Add tags to already added repos, provide way to add tags to newly added projects

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#254]
@Christian-Paul depending on how we implement this, perhaps we don't need a way to allow users to add tags at all. If the solution for tagging already added projects is good enough, maybe we just leave it automated for all new projects as well. 

Otherwise, if we go with manual, this would be in the Collaboration section of the preferences page. I can point you in the direction of the exact components if you need when we get to this point.

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack If our solution for detecting libraries/frameworks is robust enough, users probably won't need to add technology tags, but I think there would be advantages to having non-tech tags to indicate the nature of the project (music, art, AI, etc).

In that same vein, I think we should encourage users to tag their projects with tags we define, maybe with something like [this](https://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-search-selection). This would make it easier/faster to tag projects, and we can let users search by those same pre-defined tags.

This also doesn't have to prevent users from creating/searching their own original tags, as there may be value in that.

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul it didn't link to the specific example you were referring to, but we have something like that in the codebase that could serve as a good basis with the Skills/Interests section. It was actually quite a pain to get that working so that users could add their own and pull from a predefined list - mostly because I was picky about allowing users to add their own version of something we already had in the list - if it's in the list, it should default to ours regardless of case (e.g. user enters 'javascript' the tag should show up as 'JavaScript'), and adding logic to prevent repeats. This is only really difficult because we're mixing custom logic with pre-defined behaviors, but it works decently. Either way, it will be nice to not have to repeat that struggle if we go down that route. 

I think it sounds good! I like the idea of non-tech tags that you mentioned
