### ISSUE TITLE
Type on Home Page

### ISSUE THREAD

**Issue by amandeepmittal** [FCC-Alumni/alumni-network#262]
`An extension ofF the freeCodeCamp community` should be `'An extension of the freeCodeCamp community'`

**Comment by no-stack-dub-sack** [comment]
@amandeepmittal yes, good catch! would you like to submit a PR ftw?

**Comment by amandeepmittal** [comment]
@no-stack-dub-sack sure.

**Comment by amandeepmittal** [comment]
@no-stack-dub-sack Looks like the typo is already fixed with #257 since I could not find anything wrong wth (https://github.com/FCCAlumni/alumninetwork/blob/master/client/src/components/HomePage.js) this file. However the new updated version is not rendering.

**Comment by no-stack-dub-sack** [comment]
@amandeepmittal Ahhh, that's right! My bad. I forgot about that. And sorry for the late reply. 

Yeah, that PR did fix it, but my computer completely crashed, and until my new one gets here, I have no way to redeploy. Should be soon though.

**Comment by amandeepmittal** [comment]
It's alright. If you are aware of it then I think we can close the issue?

**Comment by no-stack-dub-sack** [comment]
Just redeployed, so should be fixed now. Yup, we can close :smile:
