### ISSUE TITLE
Home page improvements?

### ISSUE THREAD

**Issue by ghost** [FCC-Alumni/alumni-network#263]
Maybe it's just me, but the spinning logo on the home page made me think the page was still loading and I stared at it for half a minute before noticing the "Login" button in the top-right corner…

A nice, big "Login" button at the centre of the page would reduce the confusion, IMHO.

**Comment by no-stack-dub-sack** [comment]
@leonfeng Hey Leon! Good to see you here! I remember you from testing some of the FCC testable projects way back in 2016 (or early 2017, I can't remember). Sorry for the late reply, my notifications have been funny and there hasn't been a whole lot of activity here lately..

Anyway, hmm... this is the first time I've heard this, but I can hear where you're coming from. @bonham000 , what do you think?

I'm not sure how a big login button would look in the middle, but I'd be open to seeing what it looks like if you felt like making a PR. Thoughts?
