### ISSUE TITLE
Mock User Community for Development

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#31]
Create some way / API endpoint to pull in more GitHub user profiles to populate a demo community when developing locally in order to improve development of community/mentorship features.

(GitHub has public API we should be able to get profile data from, and we can manually populate their certificates)

**Comment by no-stack-dub-sack** [comment]
https://www.freecodecamp.com/weezlo
https://www.freecodecamp.com/mmhansen
https://www.freecodecamp.com/forkerino
https://www.freecodecamp.com/Margaret2
https://www.freecodecamp.com/sjames1958gm
https://www.freecodecamp.com/JLuboff
https://www.freecodecamp.com/0x0936
https://www.freecodecamp.com/hkuz
https://www.freecodecamp.com/coymeetsworld
https://www.freecodecamp.com/hay-dee

**Comment by no-stack-dub-sack** [comment]
@bonham000 these are all valid github and fcc usernames, all with at least one FCC certification each. Actually one coymeetsworld has more than one
