### ISSUE TITLE
coding style guide

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#42]
@stephenjfox now I see what you mean! 

@bonham000 @Bigghead @stephenjfox Interested in implementing this so we are all on the same page and keeping things consistent. I am a very visual person, and disparities in even the way the code looks can drive me up a wall 😄  (yes, I have some issues I need to work through). Nothing has really stood out to me so far, and I've mostly made consistent whatever did, but seeing as the project is getting a bit more complex, here are some thoughts I've had as far as this goes:

### JS/JSX:
- Declare functional components as expressions
- if more than 3 props, put each on own line
- keep component closing brackets on same line as last prop
- use double quotes for JSX props
- use single quotes in any other JS 
- always declare the first argument of connect as null or mapStateToProps, and declare mapStateToProps as an expression

### SCSS:
- multiple selectors should each be on their own line

* I think the cleaner and more consistently styled that we keep our codebase now, the more we'll be thanking and patting ourselves on the back later on when others might want to contribute and as things get even more complex.

**Comment by bonham000** [comment]
With the introduction of styled components (I still really have no idea how these work, by the way!), and otherwise a pretty diverse motley of styles — inline, sass, css, and our application of custom Semantic... etc. I think this would also be good, especially in relation to the Readme and Contributing guides we'll need to create: basically a uniformed set of guidelines on how you want people to implement styling, and maybe some work to make it more consistent in the codebase.

**Comment by no-stack-dub-sack** [comment]
@bonham000 I've been making this an effort in the back of my mind for some time now as I touch different parts of the codebase that I haven't touched in a while, i.e. making the style of the code more consistent. Will def have to put some deeper thought into this, but will be helpful to keep things clean when others start contributing

**Comment by stephenjfox** [comment]
Guys! I've been AWOL because of work-place unpleasantness.
Do we think there should be a formal write-up of the style guide? I've got some professional experience in that area...

**Comment by theodesp** [comment]
You don't need to spend a lot of time on this. Just add eslint and agree on a basic config like airbnb style guide with some modifications.
http://eslint.org/docs/rules/
https://github.com/airbnb/javascript

You need to make sure linting is part of the build pipeline.

**Comment by no-stack-dub-sack** [comment]
@stephenjfox I totally missed your last comment, wish I saw it back then. Hope everything has been good with you!

@theodesp originally, the issue was trying to get a custom config on top of Create-React-App's but I've since ejected and added a custom config which enforces the style rules that I care about for the most part. So going ahead and closing this.
