### ISSUE TITLE
User Profile Route

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#57]
A route specifically for viewing a user's profile, that really highlights their profile and is less of a preview (i.e. in Community page now).

e.g. `/dashboard/users/:no-stack-dub-sack`

Could link to this from community, mentorship, and chat, to give users a nice way of seeing details about another user.

Thoughts? Can discuss.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Yes, this is the next big step - I think once he have this done, we will have a pretty solid working app, and can think about cleaning things up and an initial potential release. I have more in mind for the future, but once this, chat, and search are fully done, I think we will be in good shape for an MVP (oh yeah, plus copy revisions and looking at what to do with both protected and unprotected home pages)

**Comment by no-stack-dub-sack** [comment]
@bonham000 should this be an unprotected route? so even non-users could see it? If so we'd have to hide email and such - if we even include that.
