### ISSUE TITLE
following / bookmark feature?

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#64]
Just thought of this... we should allow users to "follow" one another I think. Seems like a useful feature for something like this. 

With a community that encourages collaboration and "leveling up" by seeing where others are at in their careers, once you find someone, you should be able to follow or "bookmark" them so you can easily return to that person... Even if it's not public, so it can't become a bragging right for whoever has the most, it's just so you can find people you're interested in easily. 

There would be no "feed" involved or anything like that, no need for updates. 

Thoughts?

**Comment by bonham000** [comment]
Yeah, I think this is a cool idea and possibly one avenue the Community view could be differentiated from the Mentorship view — i.e. in Community you have an option to filter to all users you have bookmarked.

**Comment by bonham000** [comment]
I think this would be a good feature, but could be tabled to post release.
