### ISSUE TITLE
Public Profile Page

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#77]
https://github.com/FCC-Alumni/alumni-network/projects/1#card-2287024

What should we include here? There are some rather big decisions to be made (or at least 1), that will affect how folks interact with the app, and how they interact with each other. 

i.e. Should this page be "read only", and each user should only be able to change what shows here based on their "preferences" page (old profile page)? 

...OR, are we going to allow some sort of "feed" - other users would not get notifications of new posts by others or anything, but do we want to give people that "extra reason" to come back? So they can share that cool ML article they just found, or so they can see how someone else is doing with a project?

...OR simple status updates, or anything?

It might be nice to get people engaging on another level, but sure, it adds another level of complexity... 

Thoughts @bonham000?

**Comment by bonham000** [comment]
I don't think we should build any feed or status or anything for now. I actually don't think we should even build a `follow` feature.

I think the basic profile view should essentially just be a nice presentation of all the info in `preferences` and have a link to chat with the user (if we can make the routing work). From the read-only profile view we can have a link to edit in `preferences` and vice versa to 'View my Profile'.

**Comment by no-stack-dub-sack** [comment]
# #MVP

**Comment by bonham000** [comment]
Are we still entertaining the idea of a public profile page @no-stack-dub-sack? I would vote no because the key functionality of this app is between and among users, so having a public profile available to others does not add a lot in my view.

**Comment by no-stack-dub-sack** [comment]
@bonham000 I say no. Closing this issue for now.
