### ISSUE TITLE
What It Means To Be a Mentor

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#78]
Should probably have a separate route dedicated to this which provides some basic pointers and guidance, code of conduct, etc. on what it means to be a mentor in our community. Just to set some baseline expectations and what not. 

Can be simple and to the point for now - but Chance is really the one who made me think of this becuase he offered to put some questions in the next cohort placement survey pertaining to this. So maybe we'll get some useful data / insights from that which can help us build this out further.

**Comment by bonham000** [comment]
Yes I agree, hopefully our landing pages can help out with this. But just some nice content to go along with what have and fill in visitors (users and just visitors) to what the purpose of this app is.

**Comment by no-stack-dub-sack** [comment]
@bonham000 do you think we need any more info on this? The copy of the mentorship section in preferences page can def use some work, and maybe we can provide some other basic info there

**Comment by bonham000** [comment]
@no-stack-dub-sack I'm updating this now.
