### ISSUE TITLE
Github sign-in button

### ISSUE THREAD

**Issue by Bigghead** [FCC-Alumni/alumni-network#9]
The sign-in with Github button takes multiple clicks sometimes for it to register and redirects to Github for logging in

**Comment by bonham000** [comment]
I noticed that too, my guess is it's actually an `a href` you must click (the text) and if the mouse happens to be on the surrounding button itself it won't actually trigger the action.

**Comment by no-stack-dub-sack** [comment]
@Bigghead @bonham000 Yeah, I first noticed that when Shav and I were pairing yesterday - again, me being a dummy which caused it. Fixed in last night's PR.

**Comment by no-stack-dub-sack** [comment]
Closed as fixed by open pull request
